name: Build, test and publish
on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  check:
    name: Build and Check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup default stable
      - run: cargo build
      - run: cargo test
      - run: cargo publish --token ${{ secrets.CRATES_TOKEN }} --dry-run
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable
      - run: rustup default stable
      - run: cargo build
      - run: cargo test
      - run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
